# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82d0d8b06b52e9a334764ea156c67b6a3c58284638beaa5a52dd39bac22974a9d24aea300773dec8c65d8a7c3256fc07c3f8a4cceb686cbffb823fb170c76eb8

test:
  secret_key_base: 258b5898fd0cfe65ad948369e8d9f1b2e39038355e1ea78b90b20c1f36d24b37677e6e5952eefcdc89d18283a613d7185a0e3e17e200ae686c01cd4935a0bb89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
